using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
using RawPowerLabs.DynamicAI;
using RawPowerLabs.DynamicAI.Utility;
using Random = System.Random;

public class DaddyDiamond : MonoBehaviour
{
    [SerializeField] private string _diamondName;
    private TextModule _textModule;

    void Start()
    {
        var diamondPath = DiamondUtility.GetPathFromDiamondName(_diamondName);
        var context = new RawPowerLabs.DynamicAI.Context();
        var parameters = TextModuleParameters.GetDefault();
        _textModule = context.CreateTextModule(parameters, diamondPath.modelPath, diamondPath.templatePath);

        if (_textModule == null)
        {
            UnityEngine.Debug.LogError("Something went wrong with the Diamond");
        }

        PrintReplies("Test", "He is sad about his parents disowning him", "His business empire is crumbling and he's in debt", "1/3");
    }

    private async void PrintReplies(string daddy, string guess, string reason, string clues_revealed)
    {
        var replies = new Dictionary<string, string>();

        try
        {
            replies = await InvokeReplyAsync(daddy, guess, reason, clues_revealed);
        }
        catch (Exception e)
        {
            UnityEngine.Debug.LogException(e);
        }

        foreach (var reply in replies)
        {
            UnityEngine.Debug.Log($"Key: {reply.Key}, Value: {reply.Value}");
        }
    }

    public async Task<Dictionary<string, string>> InvokeReplyAsync(string daddy, string guess, string reason, string clues_revealed )
    {
        return await Task.Run(() => InvokeReply(daddy, guess, reason, clues_revealed));
    }

    public Dictionary<string, string> InvokeReply(string daddy, string guess, string reason, string clues_revealed)
    {
        if (_textModule == null)
        {
            UnityEngine.Debug.LogError("_textModule is null");
            return null;
        }

        using var textModuleInput = _textModule.CreateInput();

        textModuleInput.Set(DiamondConstants.INPUT_KEY_DADDY, daddy);
        textModuleInput.Set(DiamondConstants.INPUT_KEY_GUESS, guess);
        textModuleInput.Set(DiamondConstants.INPUT_KEY_REASON, reason);
        textModuleInput.Set(DiamondConstants.INPUT_KEY_CLUES_REVEALED, clues_revealed);

        // To get more fine-grained control over how the Diamond should invoke
        // the inputs, we also have the following TextModuleInvokeParameters class.
        // For this we can also get the default parameters.
        var invokeParameters = TextModuleInvokeParameters.GetDefault();

        // For now, it is important to remember to set the Predict Count, since
        // this value is 0 by default. This value controls the size of window that
        // the model is allowed to look forward when generating the different tokens
        // used for creating the text. If the value is zero, the generated text will be empty.
        // Try experiment with what value creates the best result for you.
        invokeParameters.PredictCount = 1024;

        // Here we set the seed, which guarantee that we will have different answers
        // generated by the Diamond. If this value is not set, the default behavior
        // is still to randomize, such that the end result is different each time. 
        var random = new Random();
        invokeParameters.Seed = (uint)random.Next(0, int.MaxValue);

        // Once we have set up both the TextModuleInvokeParameters and the inputs
        // we can invoke the Diamond. Depending on the size of the diamond, this is
        // the operation that will take some time.
        // Again we use the "using" keyword to let the compiler now, that we want it
        // to clean up the object once we are done using it.
        using var textResult = _textModule.Invoke(invokeParameters, textModuleInput);

        var replies = new Dictionary<string, string>();

        // Once the TexModule class is done invoking the input parameters,
        // we will have an object of the class TextResult. This object can be used
        // to get the output values.
        // In the same way as with inputs, we get the string values of each of the outputs by
        // using the correct key value.
        var reply = textResult.GetString(DiamondConstants.OUTPUT_REPLY);
        var game_over = textResult.GetString(DiamondConstants.OUTPUT_GAME_OVER);


        // In this example I'm using a Dictionary to keep both key and values
        // together, but you can use the values however you want.
        replies.Add(DiamondConstants.OUTPUT_REPLY, reply);
        replies.Add(DiamondConstants.OUTPUT_GAME_OVER, game_over);

        return replies;
    }
}